[[index-doc]]
=== 索引文档

可以使用 `index` API 来 _索引_ 文档&#x2014;实现文档的存储和可检索((("documents", "indexing")))((("indexing", "a document")))。但首先，我们要确定文档的位置，正如我们刚刚讨论的，一个文档的 `_index` , `_type` 和 `_id` 唯一标识这个文档。我们可以提供自己的 `_id` 值或由 `index` API自动生成。

==== 使用自己的 ID 

如果你的文档有一个天然的((("id", "providing for a document")))标识符（例如，一个 `user_account` 或者其他能标识文档的字段值），你应该使用如下的 `index` API 形式来提供自己的 `_id` ：

[role="pagebreak-before"]
[source,js]
--------------------------------------------------
PUT /{index}/{type}/{id}
{
  "field": "value",
  ...
}
--------------------------------------------------

举个例子，假如我们的索引为 `website` ，类型称为 `blog` ，并且选择  `123` 作为 ID ，那么索引请求就像这样：

[source,js]
--------------------------------------------------
PUT /website/blog/123
{
  "title": "My first blog entry",
  "text":  "Just trying this out...",
  "date":  "2014/01/01"
}
--------------------------------------------------
// SENSE: 030_Data/10_Create_doc_123.json

Elasticsearch 响应如下：

[source,js]
--------------------------------------------------
{
   "_index":    "website",
   "_type":     "blog",
   "_id":       "123",
   "_version":  1,
   "created":   true
}
--------------------------------------------------


该响应表明文档已经成功创建，该索引包括 `_index` , `_type` 和 `_id` 元数据，以及一个新元素： `_version` 。((("version number (documents)")))

在 Elasticsearch 中每个文档都有一个版本号，每次对文档进行修改时（包括删除）， `_version` 的值会递增，在<<version-control>>，我们将讨论如何使用 `_version` 确保你应用程序的一部分的修改不会覆盖另一部分所做的修改。

==== 自动生成 ID 

如果你的数据没有天然的 ID， Elasticsearch 可以帮我们自动生成 ID 。((("id", "autogenerating")))只是请求的结构发生了变化：不再用((("HTTP methods", "POST")))((("POST method"))) `PUT` 谓词(``将文档放置在 URL 中'')，我们用 `POST` 谓词(``将文档放置在 URL _之外_'')。

现在该 URL 只需包含 `_index` 和 `_type` :

[source,js]
--------------------------------------------------
POST /website/blog/
{
  "title": "My second blog entry",
  "text":  "Still trying this out...",
  "date":  "2014/01/01"
}
--------------------------------------------------
// SENSE: 030_Data/10_Create_doc_auto_ID.json

除了 `_id` 是 Elasticsearch 自动生成的，响应和我们之前看到的类似：

[source,js]
--------------------------------------------------
{
   "_index":    "website",
   "_type":     "blog",
   "_id":       "AVFgSgVHUP18jI2wRx0w",
   "_version":  1,
   "created":   true
}
--------------------------------------------------

自动生成的 ID 长度为20个字符，是 URL 安全的，基于 Base64 编码的 GUID 字符串。这些 GUID 字符串由修改的 FlakeID 体系生成，它允许多个节点同时生成唯一 ID ，且互相之间的冲突概率几乎为零。